name: mpos_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.0.0
  flutter_secure_storage: ^5.0.2
  go_router: ^3.1.1
  dio: ^4.0.6
  flutter_dotenv: ^5.0.2
  dartz: ^0.10.1
  ionicons: ^0.1.2
  flutter_spinkit: ^5.1.0
  intl: ^0.17.0
  sembast: ^3.2.0+1
  path_provider: ^2.0.11
  path: ^1.8.0
  uuid: ^3.0.6
  fluttertoast: ^8.0.7
  grouped_list: ^4.2.0
  url_launcher: ^6.1.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  assets:
    - .env
    - .env.production
    - .env.development
    - assets/
    - assets/images/

  fonts:
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Barlow-Regular
      fonts:
        - asset: assets/fonts/Barlow-Regular.ttf
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Poppins-bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Poppins-Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
      
    
  

